# Streamlit Cloud Secrets Configuration
# Copy this to your Streamlit Cloud secrets management

# AWS Configuration (optional - for production)
AWS_ACCESS_KEY_ID = "your_aws_access_key_id"
AWS_SECRET_ACCESS_KEY = "your_aws_secret_access_key"
AWS_DEFAULT_REGION = "us-east-1"

# Dashboard Configuration
COMPLIANCE_BUCKET = "your-s3-bucket-name"

# ML Model Configuration (optional)
ML_MODEL_ENDPOINT = "your-ml-endpoint-url"
API_KEY = "your-api-key"
